//namespace GoogleAdsAPI.Models
//{
//    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
//    public class Campaignss
//    {
//        public string ResourceName { get; set; }
//        public long Id { get; set; }
//        public bool HasId { get; set; }
//        public string Name { get; set; }
//        public bool HasName { get; set; }
//        public int PrimaryStatus { get; set; }
//        public List<object> PrimaryStatusReasons { get; set; }
//        public int Status { get; set; }
//        public int ServingStatus { get; set; }
//        public int BiddingStrategySystemStatus { get; set; }
//        public int AdServingOptimizationStatus { get; set; }
//        public int AdvertisingChannelType { get; set; }
//        public int AdvertisingChannelSubType { get; set; }
//        public string TrackingUrlTemplate { get; set; }
//        public bool HasTrackingUrlTemplate { get; set; }
//        public List<object> UrlCustomParameters { get; set; }
//        public object LocalServicesCampaignSettings { get; set; }
//        public object RealTimeBiddingSetting { get; set; }
//        public object NetworkSettings { get; set; }
//        public object HotelSetting { get; set; }
//        public object DynamicSearchAdsSetting { get; set; }
//        public object ShoppingSetting { get; set; }
//        public object TargetingSetting { get; set; }
//        public object AudienceSetting { get; set; }
//        public object GeoTargetTypeSetting { get; set; }
//        public object LocalCampaignSetting { get; set; }
//        public object AppCampaignSetting { get; set; }
//        public List<object> Labels { get; set; }
//        public int ExperimentType { get; set; }
//        public string BaseCampaign { get; set; }
//        public bool HasBaseCampaign { get; set; }
//        public string CampaignBudget { get; set; }
//        public bool HasCampaignBudget { get; set; }
//        public int BiddingStrategyType { get; set; }
//        public string AccessibleBiddingStrategy { get; set; }
//        public string StartDate { get; set; }
//        public bool HasStartDate { get; set; }
//        public string CampaignGroup { get; set; }
//        public bool HasCampaignGroup { get; set; }
//        public string EndDate { get; set; }
//        public bool HasEndDate { get; set; }
//        public string FinalUrlSuffix { get; set; }
//        public bool HasFinalUrlSuffix { get; set; }
//        public List<object> FrequencyCaps { get; set; }
//        public int VideoBrandSafetySuitability { get; set; }
//        public object VanityPharma { get; set; }
//        public object SelectiveOptimization { get; set; }
//        public object OptimizationGoalSetting { get; set; }
//        public object TrackingSetting { get; set; }
//        public int PaymentMode { get; set; }
//        public double OptimizationScore { get; set; }
//        public bool HasOptimizationScore { get; set; }
//        public List<object> ExcludedParentAssetFieldTypes { get; set; }
//        public List<object> ExcludedParentAssetSetTypes { get; set; }
//        public bool UrlExpansionOptOut { get; set; }
//        public bool HasUrlExpansionOptOut { get; set; }
//        public object PerformanceMaxUpgrade { get; set; }
//        public string BiddingStrategy { get; set; }
//        public object Commission { get; set; }
//        public object ManualCpa { get; set; }
//        public object ManualCpc { get; set; }
//        public object ManualCpm { get; set; }
//        public object ManualCpv { get; set; }
//        public object MaximizeConversions { get; set; }
//        public object MaximizeConversionValue { get; set; }
//        public object TargetCpa { get; set; }
//        public object TargetImpressionShare { get; set; }
//        public object TargetRoas { get; set; }
//        public object TargetSpend { get; set; }
//        public object PercentCpc { get; set; }
//        public object TargetCpm { get; set; }
//        public int CampaignBiddingStrategyCase { get; set; }
//    }

//    public class FieldMask
//    {
//        public List<string> Paths { get; set; }
//    }

//    public class Result
//    {
//        public object AccountBudget { get; set; }
//        public object AccountBudgetProposal { get; set; }
//        public object AccountLink { get; set; }
//        public object AdGroup { get; set; }
//        public object AdGroupAd { get; set; }
//        public object AdGroupAdAssetCombinationView { get; set; }
//        public object AdGroupAdAssetView { get; set; }
//        public object AdGroupAdLabel { get; set; }
//        public object AdGroupAsset { get; set; }
//        public object AdGroupAssetSet { get; set; }
//        public object AdGroupAudienceView { get; set; }
//        public object AdGroupBidModifier { get; set; }
//        public object AdGroupCriterion { get; set; }
//        public object AdGroupCriterionCustomizer { get; set; }
//        public object AdGroupCriterionLabel { get; set; }
//        public object AdGroupCriterionSimulation { get; set; }
//        public object AdGroupCustomizer { get; set; }
//        public object AdGroupExtensionSetting { get; set; }
//        public object AdGroupFeed { get; set; }
//        public object AdGroupLabel { get; set; }
//        public object AdGroupSimulation { get; set; }
//        public object AdParameter { get; set; }
//        public object AgeRangeView { get; set; }
//        public object AdScheduleView { get; set; }
//        public object DomainCategory { get; set; }
//        public object Asset { get; set; }
//        public object AssetFieldTypeView { get; set; }
//        public object AssetGroupAsset { get; set; }
//        public object AssetGroupSignal { get; set; }
//        public object AssetGroupListingGroupFilter { get; set; }
//        public object AssetGroupProductGroupView { get; set; }
//        public object AssetGroup { get; set; }
//        public object AssetSetAsset { get; set; }
//        public object AssetSet { get; set; }
//        public object AssetSetTypeView { get; set; }
//        public object BatchJob { get; set; }
//        public object BiddingDataExclusion { get; set; }
//        public object BiddingSeasonalityAdjustment { get; set; }
//        public object BiddingStrategy { get; set; }
//        public object BiddingStrategySimulation { get; set; }
//        public object BillingSetup { get; set; }
//        public object CallView { get; set; }
//        public object CampaignBudget { get; set; }
//        public Campaignss Campaign { get; set; }
//        public object CampaignAsset { get; set; }
//        public object CampaignAssetSet { get; set; }
//        public object CampaignAudienceView { get; set; }
//        public object CampaignBidModifier { get; set; }
//        public object CampaignConversionGoal { get; set; }
//        public object CampaignCriterion { get; set; }
//        public object CampaignCriterionSimulation { get; set; }
//        public object CampaignCustomizer { get; set; }
//        public object CampaignDraft { get; set; }
//        public object CampaignExtensionSetting { get; set; }
//        public object CampaignFeed { get; set; }
//        public object CampaignGroup { get; set; }
//        public object CampaignLabel { get; set; }
//        public object CampaignSharedSet { get; set; }
//        public object CampaignSimulation { get; set; }
//        public object CarrierConstant { get; set; }
//        public object ChangeEvent { get; set; }
//        public object ChangeStatus { get; set; }
//        public object CombinedAudience { get; set; }
//        public object Audience { get; set; }
//        public object ConversionAction { get; set; }
//        public object ConversionCustomVariable { get; set; }
//        public object ConversionGoalCampaignConfig { get; set; }
//        public object ConversionValueRule { get; set; }
//        public object ConversionValueRuleSet { get; set; }
//        public object ClickView { get; set; }
//        public object CurrencyConstant { get; set; }
//        public object CustomAudience { get; set; }
//        public object CustomConversionGoal { get; set; }
//        public object CustomInterest { get; set; }
//        public object Customer { get; set; }
//        public object CustomerAsset { get; set; }
//        public object CustomerAssetSet { get; set; }
//        public object AccessibleBiddingStrategy { get; set; }
//        public object CustomerCustomizer { get; set; }
//        public object CustomerManagerLink { get; set; }
//        public object CustomerClientLink { get; set; }
//        public object CustomerClient { get; set; }
//        public object CustomerConversionGoal { get; set; }
//        public object CustomerExtensionSetting { get; set; }
//        public object CustomerFeed { get; set; }
//        public object CustomerLabel { get; set; }
//        public object CustomerNegativeCriterion { get; set; }
//        public object CustomerUserAccess { get; set; }
//        public object CustomerUserAccessInvitation { get; set; }
//        public object CustomizerAttribute { get; set; }
//        public object DetailPlacementView { get; set; }
//        public object DetailedDemographic { get; set; }
//        public object DisplayKeywordView { get; set; }
//        public object DistanceView { get; set; }
//        public object DynamicSearchAdsSearchTermView { get; set; }
//        public object ExpandedLandingPageView { get; set; }
//        public object ExtensionFeedItem { get; set; }
//        public object Feed { get; set; }
//        public object FeedItem { get; set; }
//        public object FeedItemSet { get; set; }
//        public object FeedItemSetLink { get; set; }
//        public object FeedItemTarget { get; set; }
//        public object FeedMapping { get; set; }
//        public object FeedPlaceholderView { get; set; }
//        public object GenderView { get; set; }
//        public object GeoTargetConstant { get; set; }
//        public object GeographicView { get; set; }
//        public object GroupPlacementView { get; set; }
//        public object HotelGroupView { get; set; }
//        public object HotelPerformanceView { get; set; }
//        public object HotelReconciliation { get; set; }
//        public object IncomeRangeView { get; set; }
//        public object KeywordView { get; set; }
//        public object KeywordPlan { get; set; }
//        public object KeywordPlanCampaign { get; set; }
//        public object KeywordPlanCampaignKeyword { get; set; }
//        public object KeywordPlanAdGroup { get; set; }
//        public object KeywordPlanAdGroupKeyword { get; set; }
//        public object KeywordThemeConstant { get; set; }
//        public object Label { get; set; }
//        public object LandingPageView { get; set; }
//        public object LanguageConstant { get; set; }
//        public object LocationView { get; set; }
//        public object ManagedPlacementView { get; set; }
//        public object MediaFile { get; set; }
//        public object MobileAppCategoryConstant { get; set; }
//        public object MobileDeviceConstant { get; set; }
//        public object OfflineUserDataJob { get; set; }
//        public object OperatingSystemVersionConstant { get; set; }
//        public object PaidOrganicSearchTermView { get; set; }
//        public object ParentalStatusView { get; set; }
//        public object PerStoreView { get; set; }
//        public object ProductBiddingCategoryConstant { get; set; }
//        public object ProductGroupView { get; set; }
//        public object Recommendation { get; set; }
//        public object SearchTermView { get; set; }
//        public object SharedCriterion { get; set; }
//        public object SharedSet { get; set; }
//        public object SmartCampaignSetting { get; set; }
//        public object ShoppingPerformanceView { get; set; }
//        public object SmartCampaignSearchTermView { get; set; }
//        public object ThirdPartyAppAnalyticsLink { get; set; }
//        public object TopicView { get; set; }
//        public object Experiment { get; set; }
//        public object ExperimentArm { get; set; }
//        public object UserInterest { get; set; }
//        public object LifeEvent { get; set; }
//        public object UserList { get; set; }
//        public object UserLocationView { get; set; }
//        public object RemarketingAction { get; set; }
//        public object TopicConstant { get; set; }
//        public object Video { get; set; }
//        public object WebpageView { get; set; }
//        public object LeadFormSubmissionData { get; set; }
//        public object Metrics { get; set; }
//        public object Segments { get; set; }
//    }

//    public class Root
//    {
//        public List<Result> Results { get; set; }
//        public FieldMask FieldMask { get; set; }
//        public object SummaryRow { get; set; }
//        public string RequestId { get; set; }
//    }


//}
